apiVersion: v2
appVersion: v2.7.5
description: Install Rancher Server to manage Kubernetes clusters across providers.
home: https://rancher.com
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
keywords:
  - rancher
#kubeVersion: 1.27.0-0
maintainers:
  - email: charts@rancher.com
    name: Rancher Labs
name: rancher
sources:
  - https://github.com/rancher/rancher
  - https://github.com/rancher/server-chart
version: 2.7.5
